#!/bin/bash
function picture {
    mkdir ./Tree
    mkdir ./Tree/A1
    mkdir ./Tree/A2
    mkdir ./Tree/A3
    mkdir ./Tree/Personal
    mkdir ./Tree/University
    mkdir ./Tree/Hobby
    for ((i=0, t=3; i<3; i=i+1)); do
        if [ $t == 0 ]; then
        break
        fi
        random1=$RANDOM
        let "random1 %= $t"
        case $i in
            0 )
                mkdir ./Tree/A1/B1
                case $random1 in
                    0 ) 
                        mkdir ./Tree/A1/B2
                        echo "Удалите каталог В2." >> ./Task_4
                        ;;
                    1 )
                        mkdir ./Tree/A1/B2
                        mkdir ./Tree/A1/B3
                        random2=$RANDOM
                        let "random2 %= 3"
                        case $random2 in
                        0 ) echo "Удалите каталог В1." >> ./Task_4 ;;
                        1 ) echo "Удалите каталог В2." >> ./Task_4 ;;
                        2 ) echo "Удалите каталог В2." >> ./Task_4 ;;
                        esac
                        let t=t-1
                        ;;
                    2 ) let t=t+1
                esac
                ;;
            1 )
                case $random1 in
                    0 ) 
                        mkdir ./Tree/A2/C1
                        ;;
                    1 )
                        mkdir ./Tree/A2/C1
                        mkdir ./Tree/A2/C2
                        let t=t-2
                        ;;
                    2 )  
                        mkdir ./Tree/A2/C1
                        mkdir ./Tree/A2/C2
                        mkdir ./Tree/A2/C2/C3
                        let t=t-2
                        ;;
                    3 )
                        mkdir ./Tree/A2/C1
                        mkdir ./Tree/A2/C2
                        mkdir ./Tree/A2/C1/C3
                        mkdir ./Tree/A2/C2/C4
                        random2=$RANDOM
                        let "random2 %= 3"
                        case $random2 in
                        0 ) echo "Удалите каталог C1." >> ./Task_4 ;;
                        1 ) echo "Удалите каталог C2." >> ./Task_4 ;;
                        2 ) echo "Удалите каталог C2." >> ./Task_4 ;;
                        esac
                        let t=t-3
                        ;;  
                esac
                ;;
            2 )
                case $t in
                    1 ) 
                        mkdir ./Tree/A3/D1
                        ;;
                    2 )
                        mkdir ./Tree/A3/D1
                        mkdir ./Tree/A3/D1/D2
                        ;;
                    3 )
                        mkdir ./Tree/A3/D1
                        mkdir ./Tree/A3/D2
                        mkdir ./Tree/A3/D3
                        ;;
                    4 )
                        mkdir ./Tree/A3/D1
                        mkdir ./Tree/A3/D3
                        mkdir ./Tree/A3/D2
                        random2=$RANDOM
                        let "random2 %= 3"
                        case $random2 in
                        0 ) echo "Удалите каталог D1." >> ./Task_4 ;;
                        1 ) echo "Удалите каталог D2." >> ./Task_4 ;;
                        2 ) echo "Удалите каталог D2." >> ./Task_4 ;;
                        esac
                        ;;
                esac 
                ;;
        esac
    done
    tree -d ./Tree > ./tree
    rm -R ./Tree
}
function Task_4 {
    echo "Выведите содержимое каталога А1. В каталоге А1 создайте каталоги В5 и В6." >> ./Task_4
}
function Task_6 {
    random1=$RANDOM
    t=3
    let "random1 %= $t"
    case $random1 in
    0 )
        convert -background white -fill black -font DejaVu-Sans -pointsize 14 -size 1200x caption:"Множество действий в Linux могут быть осуществлены только в режиме терминала, а иногда выполнить действия в нем проще, чем в графическом режиме.\n\n601601\n\nТерминал – это программа, которая используется для взаимодействия пользователя с операционной системой. Терминал необходим для решения административных задач, таких как установка пакетов, управление пользователями, действия с файлами т. д.\n\n601601601601" Task_6.png
        ;;
    1 )
        convert -background white -fill black -font DejaVu-Sans -pointsize 14 -size 1200x caption:"Linux — это семейство операционных систем (ОС), работающих на основе одноименного ядра. Нет одной операционной системы Linux, как, например, Windows или MacOS. Есть множество дистрибутивов, выполняющих конкретные задачи.\n\n611611\n\nЛоготип и талисман Linux — пингвин Tux с желтыми лапами и клювом. В 1996 году разработчики ядра Linux решили выбрать талисман. Торвальдс обмолвился о том, что ему очень нравятся пингвины. Поэтому на логотипе ОС изображен пингвин.\n\n611611611611" Task_6.png
        ;;
    2 )
        convert -background white -fill black -font DejaVu-Sans -pointsize 14 -size 1200x caption:"Линус Торвальдс — первый разработчик и создатель Linux. Именно в честь него и была названа ОС. В 1991 году Линус начал работу над собственной ОС семейства Unix.\n\n621621\n\nЧерез три года появилась первая версия, доступная для скачивания. Но тогда она имела очень низкий спрос — ей пользовались буквально несколько человек.621621621621" Task_6.png
        ;;
    esac
}
function Task_7 {
    random1=$RANDOM
    t=3
    let "random1 %= $t"
    case $random1 in
    0 )
        echo "Объедините файлы name.txt и hobby.txt в файле all.txt каталога Info. Выведите его содержимое на экран." > Task_7
        ;;
    1 )
        echo "Объедините файлы name.txt и info.txt в файле all.txt каталога Info. Выведите его содержимое на экран." > Task_7
        ;;
    2 )
        echo "Объедините файлы info.txt и hobby.txt в файле all.txt каталога Info. Выведите его содержимое на экран." > Task_7
        ;;
    esac
}
function Task_8 {
    random1=$RANDOM
    t=3
    let "random1 %= $t"
    case $random1 in
    0 )
        echo "Скопируйте файл info.txt в каталог Info. Выведите содержимое каталога на экран." > Task_8
        ;;
    1 )
        echo "Скопируйте файл name.txt в каталог Info. Выведите содержимое каталога на экран." > Task_8
        ;;
    2 )
        echo "Скопируйте файл hobby.txt в каталог Info. Выведите содержимое каталога на экран." > Task_8
        ;;
    esac
}
function Task_9 {
    random1=$RANDOM
    t=6
    let "random1 %= $t"
    case $random1 in
    0 )
        echo "Запретите всем пользователям изменять файл all.txt и читать файл info.txt. Выведите содержимое каталога Info с ключом, позволяющем посмотреть права доступа." > Task_9
        ;;
    1 )
        echo "Запретите всем пользователям читать файл all.txt и изменять файл info.txt. Выведите содержимое каталога Info с ключом, позволяющем посмотреть права доступа." > Task_9
        ;;
    2 )
        echo "Запретите всем пользователям изменять файл all.txt и читать файл info.txt. Выведите содержимое каталога Info с ключом, позволяющем посмотреть права доступа." > Task_9
        ;;
    3 )
        echo "Запретите всем пользователям исполнять файл all.txt и читать файл info.txt. Выведите содержимое каталога Info с ключом, позволяющем посмотреть права доступа." > Task_9
        ;;
    4 )
        echo "Запретите всем пользователям изменять файл all.txt и исполнять файл info.txt. Выведите содержимое каталога Info с ключом, позволяющем посмотреть права доступа." > Task_9
        ;;
    5 )
        echo "Запретите всем пользователям исполнять файл all.txt и изменять файл info.txt. Выведите содержимое каталога Info с ключом, позволяющем посмотреть права доступа." > Task_9
        ;;
    esac
}
if ! [ -d ./Student ] 
then
    echo "В данном каталоге создаётся система каталогов и файлов для зачётного задания:"
    pwd
    mkdir Student
    cd ./Student
    Task_4
    picture
    Task_6
    Task_7
    Task_8
    Task_9
    sudo chattr +i ./Task_4
    sudo chattr +i ./Task_7
    sudo chattr +i ./Task_9
    sudo chattr +i ./Task_8
    sudo chattr +i ./tree
    echo "Система файлов и каталогов создана."
else
    echo "Ошибка. Каталог Student уже существует, удалите или перенесите его, чтобы система файлов и каталогов была создана."
fi
