#!/bin/bash
function picture {
    mkdir ./LR/LR3/Info
    mkdir ./LR/LR3/A1
    mkdir ./LR/LR3/A2
    mkdir ./LR/LR3/A3
    mkdir ./LR/LR3/Personal
    mkdir ./LR/LR3/University
    mkdir ./LR/LR3/Hobby
    for ((i=0, t=3; i<3; i=i+1)); do
        if [ $t == 0 ]; then
        break
        fi
        random1=$RANDOM
        let "random1 %= $t"
        case $i in
            0 )
                mkdir ./LR/LR3/A1/B1
                case $random1 in
                    0 ) 
                        mkdir ./LR/LR3/A1/B2
                        ;;
                    1 )
                        mkdir ./LR/LR3/A1/B2
                        mkdir ./LR/LR3/A1/B3
                        let t=t-1
                        ;;
                    2 ) let t=t+1
                esac
                ;;
            1 )
                case $random1 in
                    0 ) 
                        mkdir ./LR/LR3/A2/C1
                        ;;
                    1 )
                        mkdir ./LR/LR3/A2/C1
                        mkdir ./LR/LR3/A2/C2
                        let t=t-2
                        ;;
                    2 )  
                        mkdir ./LR/LR3/A2/C1
                        mkdir ./LR/LR3/A2/C2
                        mkdir ./LR/LR3/A2/C2/C3
                        let t=t-2
                        ;;
                    3 )
                        mkdir ./LR/LR3/A2/C1
                        mkdir ./LR/LR3/A2/C2
                        mkdir ./LR/LR3/A2/C1/C3
                        mkdir ./LR/LR3/A2/C2/C4
                        let t=t-3
                        ;;  
                esac
                ;;
            2 )
                case $t in
                    0 ) 
                        mkdir ./LR/LR3/A3/D1
                        ;;
                    1 )
                        mkdir ./LR/LR3/A3/D1
                        mkdir ./LR/LR3/A3/D1/D2
                        ;;
                    2 )
                        mkdir ./LR/LR3/A3/D1
                        mkdir ./LR/LR3/A3/D2
                        mkdir ./LR/LR3/A3/D3
                        ;;
                    3 )
                        mkdir ./LR/LR3/A3/D1
                        mkdir ./LR/LR3/A3/D3
                        mkdir ./LR/LR3/A3/D2
                        ;;
                esac 
                ;;
        esac
    done
    tree -d ./LR/LR3 > ./LR/LR3/task.txt
    rm -R ./LR/LR3/Info
    rm -R ./LR/LR3/A1
    rm -R ./LR/LR3/A2
    rm -R ./LR/LR3/A3
    rm -R ./LR/LR3/Personal
    rm -R ./LR/LR3/University
    rm -R ./LR/LR3/Hobby
}
function fun_task3 {
    declare -a task3 
    file="task3"
    i=0
    while read -r line; do
        task3[i]="$line"
        let i=i+1
    done <$file
    range=${#task3[@]}
    random1=$(( $RANDOM % $range ))
    echo "${task3[$random1]}" > ./LR/LR3/c1.txt
    random2=$(( $RANDOM % $range ))
    if [ $random1 -eq $random2 ]; then
        random2=$(( RANDOM % range ))
        if [ $random1 -eq $random2 ]; then
            random2=$((random1%range))
        fi
    fi
    echo "${task3[$random2]}" >> ./LR/LR3/c2.txt
    declare -a task1
    file="task1"
    i=0
    while read -r line; do
        task1[i]="$line"
        let i=i+1
    done <$file
    range=${#task1[@]}
    random1=$(( $RANDOM % $range ))
    echo "${task1[$random1]}" > ./LR/LR3/command2.txt
    random2=$(( $RANDOM % $range ))
    if [ $random1 -eq $random2 ]; then
        random2=$(( RANDOM % range ))
        if [ $random1 -eq $random2 ]; then
            random2=$((random1%range))
        fi
    fi
    echo "${task1[$random2]}" >> ./LR/LR3/command2.txt
}
function task_4 {
    echo -n "Установите права " > ./LR/LR4/task.txt
    random1=$RANDOM
    t=8
    let "random1 %= $t"
    echo -n "$random1" >> ./LR/LR4/task.txt
    random1=$RANDOM
    let "random1 %= $t"
    echo -n "$random1" >> ./LR/LR4/task.txt
    random1=$RANDOM
    let "random1 %= $t"
    echo -n "$random1" >> ./LR/LR4/task.txt
    random1=$RANDOM
    t=5
    let "random1 %= $t"
    case $random1 in
    0 )
        echo -n " каталогу Primer. " >> ./LR/LR4/task.txt
        random2=$RANDOM
        t=4
        let "random2 %= $t"
        case $random2 in
        0 ) 
            echo "Попробуйте просмотреть содержимое каталога." >> ./LR/LR4/task.txt
            ;;
        1 ) 
            echo "Попробуйте удалить содержимое каталога." >> ./LR/LR4/task.txt
            ;;
        2 )
            echo "Попробуйте просмотреть содержимое файла primer1.txt." >> ./LR/LR4/task.txt
            ;;
        3 )
            echo "Попробуйте просмотреть содержимое файла primer2.txt." >> ./LR/LR4/task.txt
            ;;
        esac
        ;;
    1 )
        echo -n " файлу primer1.txt. " >> ./LR/LR4/task.txt
        random2=$RANDOM
        t=3
        let "random2 %= $t"
        case $random2 in
        0 )
            echo "Попробуйте просмотреть содержимое файла primer1.txt." >> ./LR/LR4/task.txt
            ;;
        1 )
            echo "Попробуйте изменить содержимое файла primer1.txt." >> ./LR/LR4/task.txt
            ;;
        2 )
            echo "Попробуйте удалить файл primer1.txt." >> ./LR/LR4/task.txt
            ;;
        esac
        ;;
    2 )
        echo -n " файлу primer2.txt. " >> ./LR/LR4/task.txt
        random2=$RANDOM
        t=3
        let "random2 %= $t"
        case $random2 in
        0 )
            echo "Попробуйте просмотреть содержимое файла primer2.txt." >> ./LR/LR4/task.txt
            ;;
        1 )
            echo "Попробуйте изменить содержимое файла primer2.txt." >> ./LR/LR4/task.txt
            ;;
        2 )
            echo "Попробуйте удалить файл primer2.txt." >> ./LR/LR4/task.txt
            ;;
        esac
        ;;
    3 )
        echo -n " каталогу Primer и его содержимому. " >> ./LR/LR4/task.txt
        random2=$RANDOM
        t=4
        let "random2 %= $t"
        case $random2 in
        0 ) 
            echo "Попробуйте просмотреть содержимое каталога." >> ./LR/LR4/task.txt
            ;;
        1 ) 
            echo "Попробуйте удалить содержимое каталога." >> ./LR/LR4/task.txt
            ;;
        2 )
            echo "Попробуйте просмотреть содержимое файла primer1.txt." >> ./LR/LR4/task.txt
            ;;
        3 )
            echo "Попробуйте просмотреть содержимое файла primer2.txt." >> ./LR/LR4/task.txt
            ;;
        esac
        ;;
    4 )
        echo -n " файлам primer1.txt и primer2.txt. " >> ./LR/LR4/task.txt 
        random2=$RANDOM
        t=6
        let "random2 %= $t"
        case $random2 in
        0 )
            echo "Попробуйте просмотреть содержимое файла primer1.txt." >> ./LR/LR4/task.txt
            ;;
        1 )
            echo "Попробуйте изменить содержимое файла primer1.txt." >> ./LR/LR4/task.txt
            ;;
        2 )
            echo "Попробуйте удалить файл primer1.txt." >> ./LR/LR4/task.txt
            ;;
        3 )
            echo "Попробуйте просмотреть содержимое файла primer2.txt." >> ./LR/LR4/task.txt
            ;;
        4 )
            echo "Попробуйте изменить содержимое файла primer2.txt." >> ./LR/LR4/task.txt
            ;;
        5 )
            echo "Попробуйте удалить файл primer2.txt." >> ./LR/LR4/task.txt
            ;;
        esac
        ;;
    esac
    
}
if ! [ -d ./LR ] 
then
    echo -n "Вы хотите установить пакет tree? Проверьте подключение к интернету! (0 - нет; 1 - да): "
    read my_var
    if [ "$my_var" -eq 1 ]; then 
        echo "Выполняется установка. Не закрывайте терминал и не завершайте работу устройства до окончания процесса."
        sudo apt update
        sudo apt install tree
    else 
        apt list --installed tree
        echo "Если пакет не установлен, дальнейшее исполнение скрипта приведет к ошибке, вы уверены, что хотите продолжить? (0 - нет; 1 - да)"
        read my_var_1
        if [ "$my_var_1" -eq 0 ]; then 
            echo "Выполнение установки остановлено."
        else 
            echo "Выполняется установка. Не закрывайте терминал и не завершайте работу устройства до окончания процесса."
            sudo apt update
            sudo apt install tree
        fi
    fi
    mkdir LR
    cd ./LR
    echo "В данном каталоге создаётся система каталогов и файлов для выполнения лабораторных работ:"
    pwd
    cd ..
    mkdir ./LR/LR2
    declare -a task2
    file="task2"
    i=0
    while read -r line; do
        task2[i]="$line"
        let i=i+1
    done <$file
    range=${#task2[@]}
    random1=$(( $RANDOM % $range ))
    echo "${task2[$random1]}" > ./LR/LR2/command1.txt
    random2=$(( $RANDOM % $range ))
    while [ $random1 -eq $random2 ]
    do
        random2=$(( RANDOM % range ))
    done 
    echo "${task2[$random2]}" >> ./LR/LR2/command1.txt
    mkdir ./LR/LR3
    file="task3"
    picture
    fun_task3
    mkdir ./LR/LR4
    task_4
    mkdir ./LR/LR6
    mkdir ./LR/LR7
    declare -a task7
    file="task7"
    i=0
    while read -r line; do
        task7[i]="$line"
        let i=i+1
    done <$file
    range=${#task7[@]}
    random=$(( $RANDOM % $range ))
    echo -n "Пользуясь командами терминала, установите пакет " > ./LR/LR7/task.txt
    echo -n "${task7[$random]}" >> ./LR/LR7/task.txt
    echo -n ". Каково назначение этого пакета?" >> ./LR/LR7/task.txt
    sudo chattr +i ./LR/LR3/task.txt
    sudo chattr +i ./LR/LR3/command2.txt
    sudo chattr +i ./LR/LR2/command1.txt
    sudo chattr +i ./LR/LR4/task.txt
    sudo chattr +i ./LR/LR7/task.txt
    echo "Система файлов и каталогов создана."
else
    echo "Ошибка. Каталог LR уже существует, удалите или перенесите его, чтобы система файлов и каталогов была создана."
fi
